In [2]:
import pandas as pd
import numpy as np
df = pd.read_excel('Auction_HK_2016-2020 final .xlsx')

In [3]:
df=df.drop(['artist','title','created'],axis=1)

In [4]:
df = pd.get_dummies(df)

In [5]:
df=df.dropna()

In [6]:
df=df.reset_index(drop=True)

In [7]:
df

sales_price  sales_price_log  estimate_range  auction_location  \
0          240190        12.389186         25620.0                 0   
1         1252180        14.040397        256200.0                 0   
2         1282920        14.064649        256200.0                 0   
3          224180        12.320205         38430.0                 0   
4        16752020        16.634029       1281000.0                 0   
...           ...              ...             ...               ...   
4189        30600        10.328755         15400.0                 1   
4190        26010        10.166236          7700.0                 1   
4191        48960        10.798759         12840.0                 1   
4192        24480        10.105612          7700.0                 1   
4193        39780        10.591120          7700.0                 1   

       surface  artist_seal  inscribed  signed  dated  titled  ...  panel  \
0       924.00            0          0       1      0       0  ...      0   
1      3510.78            0          0       0      0       0  ...      0   
2      4611.00            0          0       0      0       0  ...      0   
3      1262.24            0          0       0      0       0  ...      0   
4     10905.25            0          0       1      1       0  ...      0   
...        ...          ...        ...     ...    ...     ...  ...    ...   
4189  16030.00            0          0       0      0       0  ...      0   
4190  22500.00            0          0       0      0       0  ...      0   
4191  21010.50            0          0       0      0       0  ...      0   
4192   8778.50            0          0       0      0       0  ...      0   
4193   5950.00            0          0       0      0       0  ...      0   

      ink  wood  auction_weekday_Friday  auction_weekday_Monday  \
0       0     0                       0                       0   
1       0     0                       0                       0   
2       0     0                       0                       0   
3       0     0                       0                       0   
4       0     0                       0                       0   
...   ...   ...                     ...                     ...   
4189    1     0                       0                       1   
4190    1     0                       0                       1   
4191    1     0                       0                       1   
4192    1     0                       0                       1   
4193    1     0                       0                       1   

      auction_weekday_Saturday  auction_weekday_Sunday  \
0                            0                       1   
1                            0                       1   
2                            0                       1   
3                            0                       1   
4                            0                       1   
...                        ...                     ...   
4189                         0                       0   
4190                         0                       0   
4191                         0                       0   
4192                         0                       0   
4193                         0                       0   

      auction_weekday_Thursday  auction_weekday_Tuesday  \
0                            0                        0   
1                            0                        0   
2                            0                        0   
3                            0                        0   
4                            0                        0   
...                        ...                      ...   
4189                         0                        0   
4190                         0                        0   
4191                         0                        0   
4192                         0                        0   
4193                         0                        0   

     

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
df=df.drop(df[(df['sales_price']<25000)].index)

In [10]:
df=df.drop(df[(df['sales_price']>300000)].index)

In [32]:
df=df.reset_index(drop=True)

In [33]:
df

sales_price  sales_price_log  estimate_range  auction_location  \
0          240190        12.389186         25620.0                 0   
1          224180        12.320205         38430.0                 0   
2          272210        12.514329        102480.0                 0   
3          256200        12.453714        166530.0                 0   
4          160130        11.983741         25620.0                 0   
...           ...              ...             ...               ...   
2073        42840        10.665228         16690.0                 1   
2074        30600        10.328755         15400.0                 1   
2075        26010        10.166236          7700.0                 1   
2076        48960        10.798759         12840.0                 1   
2077        39780        10.591120          7700.0                 1   

       surface  artist_seal  inscribed  signed  dated  titled  stamped  \
0       924.00            0          0       1      0       0        0   
1      1262.24            0          0       0      0       0        0   
2     13566.00            0          0       1      1       0        0   
3     10000.00            0          0       1      1       0        0   
4      6597.50            0          0       1      1       0        0   
...        ...          ...        ...     ...    ...     ...      ...   
2073   9000.00            0          0       1      1       0        0   
2074  16030.00            0          0       0      0       0        0   
2075  22500.00            0          0       0      0       0        0   
2076  21010.50            0          0       0      0       0        0   
2077   5950.00            0          0       0      0       0        0   

      auction_year  auction_month  canvas  oil  acrylic  board  paper  \
0             2019              3       0    1        0      1      1   
1             2019              3       1    1        0      0      0   
2             2019              3       1    0        1      0      0   
3             2019              3       1    0        1      0      0   
4             2019              3       1    1        0      0      0   
...            ...            ...     ...  ...      ...    ...    ...   
2073          2017              5       0    1        0      0      0   
2074          2017              5       0    0        1      0      1   
2075          2017              5       1    0        1      0      0   
2076          2017              5       1    0        1      0      0   
2077          2017              5       1    0        1      0      0   

      lacquer  masonite  panel  ink  wood  auction_weekday_Friday  \
0           0         0      0    0     0                       0   
1           0         0      0    0     0                       0   
2           0         0      0    0     0                       0   
3           0         0      0    0     0                       0   
4           0         0      0    0     0                       0   
...       ...       ...    ...  ...   ...                     ...   
2073        0         0      0    0     0                       0   
2074        0         0      0    1     0                       0   
2075        0         0      0    1     0                       0   
2076        0         0      0    1     0                       0   
2077        0         0      0    1     0                       0   

      auction_weekday_Monday  auction_weekday_Saturday  \
0                          0                         0   
1                          0                         0   
2                          0                         0   
3                          0                         0   
4                          0                         0   
...                      ...                       ...   
2073                       0                         0   
2074                       1                         0   
2075                    

In [12]:
y = df["sales_price"]
x=df.drop(['sales_price','sales_price_log'],axis=1)

In [13]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.50, random_state=42)

In [14]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 2000 decision trees
rf = RandomForestRegressor(n_estimators = 3000, random_state = 42)
# Train the model on training data
rf.fit(x_train,y_train);

In [15]:
# Use the forest's predict method on the test data
y_pred = rf.predict(x_test)
# Calculate the absolute errors
errors = abs(y_pred - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 35332.5 degrees.


In [16]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 0), '%.')

Accuracy: 55.0 %.


In [17]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
print('MAE: ', mean_absolute_error(y_test, y_pred))
print('MSE: ', mean_squared_error(y_test, y_pred)) 

MAE:  35332.49779588127
MSE:  2357417708.020985


In [18]:
random_forest_out_of_bag = RandomForestRegressor(oob_score=True)
random_forest_out_of_bag.fit(x_train, y_train)
print(random_forest_out_of_bag.oob_score_) 

0.4959375656165218


In [19]:
rf.score(x_test, y_test).round(10)

0.5436428385

In [20]:
rf.score(x_train, y_train).round(10)

0.9337419551

In [22]:
y_test_pred = rf.predict(x_test)

In [23]:
data_new = x_train[15:23]

In [24]:
data_new

estimate_range  auction_location   surface  artist_seal  inscribed  \
3767         19320.0                 1   7320.00            0          1   
1121         89670.0                 0  10074.00            0          0   
499         128100.0                 0  13216.50            0          0   
1533          6440.0                 0   8190.75            0          0   
3733         12880.0                 1   1353.00            0          0   
669           3840.0                 0  45000.00            0          0   
2848         51240.0                 1   4841.76            0          0   
2853         38430.0                 1  22500.00            0          0   

      signed  dated  titled  stamped  auction_year  auction_month  canvas  \
3767       1      0       0        0          2016              5       0   
1121       1      1       0        0          2018              3       1   
499        1      1       0        0          2019             10       1   
1533       1      0       0        0          2017              4       1   
3733       1      1       0        0          2016              5       1   
669        1      1       0        0          2018             10       1   
2848       0      0       0        0          2018             11       1   
2853       1      1       0        0          2018             11       1   

      oil  acrylic  board  paper  lacquer  masonite  panel  ink  wood  \
3767    1        0      1      0        0         1      0    0     0   
1121    1        0      0      0        0         0      0    0     0   
499     1        0      0      0        0         0      0    0     0   
1533    1        0      0      0        0         0      0    0     0   
3733    1        0      0      0        0         0      0    0     0   
669     1        0      0      0        0         0      0    0     0   
2848    1        0      0      0        0         0      0    0     0   
2853    1        0      0      0        0         0      0    0     0   

      auction_weekday_Friday  auction_weekday_Monday  \
3767                       0                       0   
1121                       0                       0   
499                        0                       0   
1533                       0                       1   
3733                       0                       0   
669                        0                       1   
2848                       0                       0   
2853                       0                       0   

      auction_weekday_Saturday  auction_weekday_Sunday  \
3767                         0                       1   
1121                         1                       0   
499                          0                       1   
1533                         0                       0   
3733                         0                       1   
669                          0                       0   
2848                         0                       1   
2853                         0                       1   

      auction_weekday_Thursday  auction_weekday_Tuesday  \
3767                         0                        0   
1121                         0                        0   
499                          0                        0   
1533                         0                        0   
3733                         0                        0   
669                          0                        0   
2848                         0                        0   
2853                         0                        0   

      auction_weekday_Wednesday  
3767                          0  
1121                          0  
499                           0  
1533                          0  
3733                          0  
669                           0  
2848                          0  
2853                          0

In [25]:
rf.predict(data_new)

array([ 65760.78      , 228630.52333333, 247164.69      ,  41677.88      ,
        60636.89      ,  30805.53      , 134600.29      , 145279.37666667])

In [26]:
y_train[15:23]

3767     58140
1121    240190
499     256200
1533     38610
3733     61200
669      27220
2848    122410
2853    145360
Name: sales_price, dtype: int64

In [27]:
import sklearn.metrics as sm
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, y_test_pred), 2)) 
print("Mean squared error =", round(sm.mean_squared_error(y_test, y_test_pred), 2)) 
print("Median absolute error =", round(sm.median_absolute_error(y_test, y_test_pred), 2)) 
print("Explain variance score =", round(sm.explained_variance_score(y_test, y_test_pred), 2)) 
print("R2 score =", round(sm.r2_score(y_test, y_test_pred), 2))

Mean absolute error = 35332.5
Mean squared error = 2357417708.02
Median absolute error = 25149.36
Explain variance score = 0.54
R2 score = 0.54


In [36]:
df.loc[89:91]

sales_price  sales_price_log  estimate_range  auction_location   surface  \
89        64050        11.067419         12810.0                 0  21141.00   
90       128100        11.760566         89670.0                 0  30000.00   
91        38430        10.556594          8970.0                 0   2237.29   

    artist_seal  inscribed  signed  dated  titled  stamped  auction_year  \
89            0          0       1      1       0        0          2019   
90            0          0       1      1       0        0          2019   
91            0          0       1      1       0        0          2019   

    auction_month  canvas  oil  acrylic  board  paper  lacquer  masonite  \
89              4       1    1        0      0      0        0         0   
90              4       0    1        0      0      0        0         0   
91              4       1    1        0      0      0        0         0   

    panel  ink  wood  auction_weekday_Friday  auction_weekday_Monday  \
89      0    0     0                       0                       1   
90      0    0     0                       0                       1   
91      0    0     0                       0                       1   

    auction_weekday_Saturday  auction_weekday_Sunday  \
89                         0                       0   
90                         0                       0   
91                         0                       0   

    auction_weekday_Thursday  auction_weekday_Tuesday  \
89                         0                        0   
90                         0                        0   
91                         0                        0   

    auction_weekday_Wednesday  
89                          0  
90                          0  
91                          0

In [39]:
x.shape

(2078, 28)

In [40]:
y.shape

(2078,)

In [42]:
rf.predict([[89670.0,0,30000.00,0,0,1,1,0,0,2019,4,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0]])

C:\Users\devj7\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([145613.54333333])

In [43]:
df.loc[1099:1100]

sales_price  sales_price_log  estimate_range  auction_location  surface  \
1099        53550        10.888371          7680.0                 1   4380.0   
1100        84160        11.340475          7680.0                 1   5980.0   

      artist_seal  inscribed  signed  dated  titled  stamped  auction_year  \
1099            0          0       1      1       0        0          2017   
1100            0          0       1      1       0        0          2017   

      auction_month  canvas  oil  acrylic  board  paper  lacquer  masonite  \
1099             11       0    1        0      1      0        0         0   
1100             11       1    1        0      0      0        0         0   

      panel  ink  wood  auction_weekday_Friday  auction_weekday_Monday  \
1099      0    0     0                       0                       0   
1100      0    0     0                       0                       0   

      auction_weekday_Saturday  auction_weekday_Sunday  \
1099                         0                       1   
1100                         0                       1   

      auction_weekday_Thursday  auction_weekday_Tuesday  \
1099                         0                        0   
1100                         0                        0   

      auction_weekday_Wednesday  
1099                          0  
1100                          0

In [53]:
rf.predict([[7680.0,1,4380.0,0,0,1,1,0,0,2017,11,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0]])

C:\Users\devj7\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([51226.38571429])

In [52]:
rf.predict([[76800.0,0,2000.0,1,0,1,1,0,0,2017,4,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0]])

C:\Users\devj7\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([178502.])